import type { DebriefReport, ScenarioConfig } from './types.ts'
import { personaFor } from './guideContent.ts'
import { GRADE_DESCRIPTION, letterGrade } from './grading.ts'

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function scorecardSubject(scenario: ScenarioConfig, report: DebriefReport): string {
  const overall = letterGrade(report.overallScore, report.overallMaxScore)
  return `Worksite Trainer Scorecard: ${overall} — ${scenario.agentName} (${personaFor(scenario.businessId).label})`
}

export function scorecardHtml(scenario: ScenarioConfig, report: DebriefReport): string {
  const persona = personaFor(scenario.businessId)
  const overallGrade = letterGrade(report.overallScore, report.overallMaxScore)

  const rows = report.rubric
    .map((r) => {
      const g = letterGrade(r.score, r.maxScore)
      return `
        <tr>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;color:#1f2937;">${escapeHtml(r.category)}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;color:#1f2937;font-weight:700;text-align:center;">${g}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#6b7280;">${escapeHtml(r.feedback)}</td>
        </tr>`
    })
    .join('')

  const list = (items: string[]) =>
    items.length ? `<ul style="margin:6px 0 0;padding-left:18px;">${items.map((i) => `<li style="font-size:13px;color:#374151;margin-bottom:4px;">${escapeHtml(i)}</li>`).join('')}</ul>` : '<p style="font-size:13px;color:#9ca3af;margin:6px 0 0;">None noted.</p>'

  return `
  <div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto;color:#111827;">
    <div style="background:#0c1220;padding:24px;border-radius:12px 12px 0 0;">
      <p style="margin:0;font-size:12px;letter-spacing:0.05em;text-transform:uppercase;color:#e8b64a;font-weight:700;">Whittingham Agency — Worksite Trainer</p>
      <h1 style="margin:6px 0 0;font-size:22px;color:#ffffff;">${escapeHtml(report.headline)}</h1>
    </div>
    <div style="border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px;padding:24px;">
      <p style="font-size:13px;color:#6b7280;margin:0 0 16px;">
        ${escapeHtml(scenario.agentName)} · ${escapeHtml(persona.label)} · ${escapeHtml(scenario.difficulty)} difficulty
      </p>

      <div style="display:flex;align-items:center;gap:16px;background:#f9fafb;border-radius:10px;padding:16px;margin-bottom:20px;">
        <div style="font-size:40px;font-weight:800;color:#111827;">${overallGrade}</div>
        <div>
          <div style="font-size:14px;font-weight:600;color:#111827;">${report.overallScore}/${report.overallMaxScore} overall</div>
          <div style="font-size:12px;color:#6b7280;">${escapeHtml(GRADE_DESCRIPTION[overallGrade])}</div>
        </div>
      </div>

      <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
        <thead>
          <tr>
            <th style="text-align:left;padding:8px 12px;font-size:11px;text-transform:uppercase;color:#9ca3af;border-bottom:2px solid #e5e7eb;">Section</th>
            <th style="text-align:center;padding:8px 12px;font-size:11px;text-transform:uppercase;color:#9ca3af;border-bottom:2px solid #e5e7eb;">Grade</th>
            <th style="text-align:left;padding:8px 12px;font-size:11px;text-transform:uppercase;color:#9ca3af;border-bottom:2px solid #e5e7eb;">Notes</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>

      <h2 style="font-size:14px;color:#059669;margin:0 0 4px;">Strengths</h2>
      ${list(report.strengths)}

      <h2 style="font-size:14px;color:#b45309;margin:16px 0 4px;">To Improve</h2>
      ${list(report.improvements)}

      <h2 style="font-size:14px;color:#111827;margin:16px 0 4px;">Script Deviations</h2>
      ${list(report.scriptDeviations)}

      <h2 style="font-size:14px;color:#1d4ed8;margin:16px 0 4px;">Next Drill</h2>
      <p style="font-size:13px;color:#374151;margin:6px 0 0;">${escapeHtml(report.nextDrill)}</p>

      <p style="font-size:11px;color:#9ca3af;margin-top:24px;border-top:1px solid #e5e7eb;padding-top:12px;">
        Generated by the Whittingham Agency Worksite Trainer role-play simulator. Not an official Globe Life
        Liberty National Division performance record.
      </p>
    </div>
  </div>`
}

export function scorecardText(scenario: ScenarioConfig, report: DebriefReport): string {
  const persona = personaFor(scenario.businessId)
  const overallGrade = letterGrade(report.overallScore, report.overallMaxScore)
  const lines = [
    `Worksite Trainer Scorecard`,
    `${scenario.agentName} — ${persona.label} — ${scenario.difficulty} difficulty`,
    '',
    `Overall: ${overallGrade} (${report.overallScore}/${report.overallMaxScore})`,
    report.headline,
    '',
    ...report.rubric.map((r) => `${r.category}: ${letterGrade(r.score, r.maxScore)} (${r.score}/${r.maxScore}) — ${r.feedback}`),
    '',
    'Strengths:',
    ...report.strengths.map((s) => `- ${s}`),
    '',
    'To Improve:',
    ...report.improvements.map((s) => `- ${s}`),
    '',
    'Script Deviations:',
    ...report.scriptDeviations.map((s) => `- ${s}`),
    '',
    `Next Drill: ${report.nextDrill}`,
  ]
  return lines.join('\n')
}
